import Header from '@/components/layouts/Header'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Make salesforce easy to use | Laserfocus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://laserfocus.io/favicon.svg" />
      </Head>
      <main className=''>
        <Header />
      </main>
    </>
  )
}
