import Companies from '@/components/layouts/Companies'
import Header from '@/components/layouts/Header'
import MainPage from '@/components/layouts/MainPage'
import OtherSections from '@/components/layouts/OtherSections'
import ProductDisplay from '@/components/layouts/ProductDisplay'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Make salesforce easy to use | Laserfocus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://laserfocus.io/favicon.svg" />
      </Head>
      <main className=''>
        <Header />
        <MainPage />
        <ProductDisplay />
        <Companies />
        <OtherSections />
      </main>
    </>
  )
}
